version: '3.1'

services:

  db:
    image: mysql:8.1.0
    platform: linux/amd64
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: titicaca
      MYSQL_DATABASE: car_information
      MYSQL_USER: car_information_user
      MYSQL_PASSWORD: titicaca